Repository HJNYJ/mediDoc, pull requests merged in 2024-04, with the labels that each got.

#4 Feat/apply - 예약신청페이지 구현완료 및 메인페이지 구현중
  src/api/supabase.ts
  src/app/home/page.tsx
  src/app/layout.tsx
  src/assets/check.png
  src/components/apply/ApplyPageFour.tsx
  src/components/apply/ApplyPageOne.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/ApplyPageTwo.tsx
  src/components/apply/CourseSelect.tsx
  src/components/apply/GetNewData.tsx
  src/components/apply/HospitalName.tsx
  src/components/apply/TimeSelect.tsx
  src/components/apply/VisitorInfo.tsx
  src/components/home/FindHospital.tsx
  src/components/home/HospitalList.tsx
  src/components/home/HospitalListView.tsx
  src/components/home/search/FindHospitalRegionBtn.tsx
  src/components/layout/Navbar.tsx
  src/components/map/hospitalList/HospitalList.tsx
  src/hooks/getHospitalData.ts
  src/shared/zustand/applyStore.ts
  src/types/index.ts
  src/types/supabase.ts
Labels: 기능 구현, 문제 해결

#6 consult hospital staff 분류
  src/api/supabase.ts
  src/app/consult/[consultId]/page.tsx
  src/app/hospital/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/components/consult/ConsultAnswerForm.tsx
  src/components/map/defaultTab/ReviewList.tsx
  src/components/map/imageTab/ImageTab.tsx
  src/components/map/review/ReviewItem.tsx
  src/components/map/reviewTab/ReviewTab.tsx
Labels: 기능 구현

#7 마이페이지 퍼블리싱 진행 중
  src/app/mypage/[userId]/page.tsx
  src/components/layout/ Buttons.tsx
  src/components/layout/Navbar.tsx
  src/components/mypage/AccessDenied.tsx
  src/components/mypage/MyPageTab.tsx
  src/components/mypage/MyQuestionItem.tsx
  src/components/mypage/ReservationInfoItem.tsx
  src/components/mypage/ReservationInfoList.tsx
  src/components/mypage/ScrappedList.tsx
Labels: 기능 구현, 파일 수정

#10 Feat/mainpage 메인페이지 카테고리(지역 별) 병원 나누기 / 단건조회 시 해당 병원의 DB 출력 구현중
  src/app/home/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/layout/Navbar.tsx
  src/components/map/HospitalMainInfo.tsx
  src/components/map/defaultTab/ReviewImageList.tsx
  src/components/map/defaultTab/ReviewList.tsx
  src/components/map/review/ReviewItem.tsx
  src/components/map/review/ReviewRecent.tsx
  src/components/map/reviewTab/ReviewTab.tsx
  src/types/supabase.ts
Labels: 기능 구현, 도움이 필요함

#11 consult form CSS 수정
  src/app/consult/[consultId]/page.tsx
  src/components/consult/ConsultTabs.tsx
  src/components/map/HospitalMainInfo.tsx
  src/components/map/defaultTab/DefaultTab.tsx
  src/components/map/defaultTab/ReviewList.tsx
  src/components/map/hospitalList/HospitalList.tsx
  src/components/map/imageTab/ImageTab.tsx
  src/components/map/review/ReviewForm.tsx
  src/components/map/review/ReviewRating.tsx
  src/components/map/review/ReviewTags.tsx
  src/components/map/reviewTab/ReviewTab.tsx
  src/types/supabase.ts
Labels: 기능 구현

#13 Feat/selftest
  src/app/selftest/page.tsx
  src/components/layout/Button.tsx
  src/components/selftest/BodyParts.tsx
  src/components/selftest/Departments.tsx
  src/components/selftest/Genders.tsx
  src/components/selftest/Symptoms.tsx
Labels: 기능 구현, 파일 수정

#14 마이페이지 퍼블리싱 진행 중
  src/app/mypage/[userId]/page.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/GetNewData.tsx
  src/components/layout/ Buttons.tsx
  src/components/layout/ Tabs.tsx
  src/components/layout/Buttons.tsx
  src/components/mypage/MyPageTab.tsx
  src/components/mypage/ReservationInfoItem.tsx
  src/types/index.ts
  tailwind.config.ts
Labels: 기능 구현, 파일 수정

#18 로그인 페이지, Navbar 퍼블리싱 완료
  src/app/login/page.tsx
  src/assets/icons/HomeIndicator.png
  src/assets/icons/StatusBar.png
  src/assets/icons/consultIcon.png
  src/assets/icons/googlelogin.png
  src/assets/icons/homeIcon.png
  src/assets/icons/kakaologin.png
  src/assets/icons/loginIcon.png
  src/assets/icons/logoutIcon.png
  src/assets/icons/mypageIcon.png
  src/assets/icons/testIcon.png
  src/components/layout/Button.tsx
  src/components/layout/HomeIndicator.tsx
  src/components/layout/Navbar.tsx
  src/components/layout/StatusBar.tsx
  src/components/layout/Tabs.tsx
  src/components/mypage/MyPageTab.tsx
  src/hooks/browserClient.ts
  src/hooks/clientSession.ts
  src/hooks/useSession.ts
  src/types/supabase.ts
Labels: 기능 구현, 파일 수정

#19 자가진단 페이지, 랜딩 페이지 퍼블리싱 진행 중
  src/app/mypage/[userId]/page.tsx
  src/app/page.tsx
  src/app/selftest/page.tsx
  src/assets/icons/selftest/Female_checked.png
  src/assets/icons/selftest/Female_not_checked.png
  src/assets/icons/selftest/Male_checked.png
  src/assets/icons/selftest/Male_not_checked.png
  src/assets/icons/selftest/ear_disease.jpeg
  src/assets/icons/selftest/previousmark.png
  src/assets/icons/selftest/progress_step1.png
  src/assets/icons/selftest/progress_step2.png
  src/assets/icons/selftest/progress_step3.png
  src/assets/icons/selftest/progress_step4.png
  src/assets/icons/selftest/xmark.png
  src/assets/landing/landing1.png
  src/assets/landing/landing2.png
  src/assets/landing/landing3.png
  src/assets/landing/landing4.png
  src/components/layout/Buttons.tsx
  src/components/layout/CheckIcons.tsx
  src/components/layout/Navbar.tsx
  src/components/selftest/BodyParts.tsx
  src/components/selftest/Departments.tsx
  src/components/selftest/Genders.tsx
  src/components/selftest/Symptoms.tsx
  src/components/selftest/TestResult.tsx
Labels: 기능 구현, 파일 수정

#22 consult form, answer, list 퍼블리싱 및 consult 이미지 렌더링 에러 수정
  package.json
  src/api/supabase.ts
  src/app/consult/[consultId]/page.tsx
  src/app/consult/ask/page.tsx
  src/app/consult/page.tsx
  src/app/globals.css
  src/app/hospital/review/page.tsx
  src/app/page.tsx
  src/assets/icons/consult/add.png
  src/assets/icons/consult/answer_complete.png
  src/assets/icons/consult/answer_wait.png
  src/assets/icons/consult/camera.png
  src/assets/icons/consult/check.png
  src/assets/icons/consult/imagebox.png
  src/assets/icons/consult/okBtn.png
  src/assets/icons/consult/searchbar.png
  src/assets/icons/consult/selectDiagnosis.png
  src/assets/icons/review/review_searchbar.png
  src/components/consult/AskForm.tsx
  src/components/consult/ConsultAnswerForm.tsx
  src/components/consult/ConsultNotice.tsx
  src/components/consult/ConsultTabs.tsx
  src/components/consult/HashTags.tsx
  src/components/layout/RoundTabs.tsx
  src/components/map/review/ReviewForm.tsx
  src/components/map/review/ReviewRating.tsx
  src/components/map/review/ReviewTags.tsx
  src/types/supabase.ts
  src/utils/hashtag.tsx
  yarn.lock
Labels: 기능 구현

#23 마이페이지, 메인페이지, 병원 페이지 퍼블리싱 진행 중
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/map/[hospitalId]/page.tsx
  src/app/map/page.tsx
  src/app/mypage/[userId]/page.tsx
  src/app/page.tsx
  src/app/selftest/page.tsx
  src/assets/icons/bookmark.png
  src/assets/icons/date.png
  src/assets/icons/down.png
  src/assets/icons/main/강원.png
  src/assets/icons/main/경기.png
  src/assets/icons/main/경상.png
  src/assets/icons/main/서울.png
  src/assets/icons/main/인천.png
  src/assets/icons/main/전라.png
  src/assets/icons/main/제주.png
  src/assets/icons/main/충청.png
  src/assets/icons/modal/course.png
  src/assets/icons/modal/date.png
  src/assets/icons/modal/hospital.png
  src/assets/icons/modal/reservation_id.png
  src/assets/icons/modal/status.png
  src/assets/icons/modal/subject_name.png
  src/assets/icons/nextIcon.png
  src/assets/icons/phone.png
  src/assets/icons/previousIcon.png
  src/assets/icons/searchIcon.png
  src/assets/icons/star.png
  src/assets/icons/xmark.png
  src/components/home/FindHospital.tsx
  src/components/home/HospitalListView.tsx
  src/components/home/search/FindHospitalRegionBtn.tsx
  src/components/layout/Buttons.tsx
  src/components/layout/Navbar.tsx
  src/components/layout/TopNavbar.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/Map.tsx
  src/components/map/hospitalList/HospitalItem.tsx
  src/components/mypage/ReservationInfoItem.tsx
  src/utils/checkHospitalOpen.ts
Labels: 기능 구현, 파일 수정

#24 Feat/apply - 예약신청 페이지 퍼블리싱 작업 및 진행바, 버튼 컴포넌트 수정
  src/assets/upanddown/down_toggle.png
  src/assets/upanddown/up_toggle.png
  src/components/apply/ApplyPageFour.tsx
  src/components/apply/ApplyPageOne.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/ApplyPageTwo.tsx
  src/components/apply/CalendarDay.tsx
  src/components/apply/CourseSelect.tsx
  src/components/apply/GetNewData.tsx
  src/components/apply/HospitalName.tsx
  src/components/apply/TimeSelect.tsx
  src/components/consult/AskForm.tsx
  src/components/layout/CheckIcons.tsx
  src/components/layout/GrayBar.tsx
  src/components/layout/GrayBarMg.tsx
  src/components/layout/YellowBar.tsx
  src/components/layout/YellowBarMg.tsx
  src/components/selftest/Departments.tsx
Labels: 기능 구현, 문제 해결, 파일 수정

#26 review id 값 나누기, 기존 hospital 폴더 삭제
  src/api/supabase.ts
  src/app/consult/[consultId]/page.tsx
  src/app/consult/ask/page.tsx
  src/app/hospital/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/app/map/[hospitalId]/review/page.tsx
  src/assets/icons/check.png
  src/assets/icons/review/review_okBtn.png
  src/components/apply/GetNewData.tsx
  src/components/consult/AskForm.tsx
  src/components/home/search/FindHospitalRegionBtn.tsx
  src/components/map/HospitalMainInfo.tsx
  src/components/map/defaultTab/DefaultTab.tsx
  src/components/map/defaultTab/ReviewList.tsx
  src/components/map/review/ReviewForm.tsx
  src/components/map/review/ReviewItem.tsx
  src/components/map/review/ReviewRating.tsx
  src/components/map/review/ReviewTags.tsx
  src/components/map/reviewTab/ReviewTab.tsx
Labels: 기능 구현, 파일 수정

#29 Feat/selftest
  declarations.d.ts
  package.json
  src/api/supabase.ts
  src/app/apply/[hospitalId]/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/assets/icons/bookmark_checked.png
  src/components/apply/ApplyPageOne.tsx
  src/components/apply/HospitalName.tsx
  src/components/layout/Slider.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/mypage/ScrappedList.tsx
  src/shared/zustand/scrapStore.ts
  src/utils/changeScrappedList.ts
  src/utils/getUserId.ts
  yarn.lock
Labels: 기능 구현, 문제 해결, 파일 수정

#32 랜딩 페이지, 자가 진단페이지, 로그인 페이지, 병원 상세페이지 수정
  package.json
  src/app/globals.css
  src/app/login/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/app/map/[hospitalId]/review/page.tsx
  src/app/page.tsx
  src/app/selftest/page.tsx
  src/assets/landing/Page1.png
  src/assets/landing/Page2.png
  src/assets/landing/Page3.png
  src/assets/landing/Page4.png
  src/assets/landing/landing1.png
  src/assets/landing/landing2.png
  src/assets/landing/landing3.png
  src/assets/landing/landing4.png
  src/components/apply/ApplyPageOne.tsx
  src/components/layout/Navbar.tsx
  src/components/layout/Slider.tsx
  src/components/layout/Tabs.tsx
  src/components/selftest/Departments.tsx
  src/components/selftest/Genders.tsx
  src/components/selftest/Symptoms.tsx
  src/shared/zustand/selftestStore.ts
  src/types/supabase.ts
  yarn.lock
Labels: 기능 구현, 문제 해결, 파일 수정

#34 Feat/apply - 예약신청페이지 기능 및 구현완료 / 자가진단페이지 퍼블리싱 작업 / 병원이름 DB저장 및 보여주기 구현
  src/app/globals.css
  src/app/selftest/page.tsx
  src/assets/check.png
  src/components/apply/ApplyPageFour.tsx
  src/components/apply/ApplyPageOne.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/ApplyPageTwo.tsx
  src/components/apply/CalendarDay.tsx
  src/components/apply/CourseSelect.tsx
  src/components/apply/GetNewData.tsx
  src/components/apply/HospitalName.tsx
  src/components/home/HospitalListView.tsx
  src/components/layout/CheckIcons.tsx
  src/components/layout/PageBackBtn.tsx
  src/components/layout/PageCancel.tsx
  src/components/selftest/BodyParts.tsx
  src/components/selftest/Departments.tsx
  src/components/selftest/Genders.tsx
  src/components/selftest/Symptoms.tsx
  src/shared/zustand/applyStore.ts
  src/types/supabase.ts
Labels: 기능 구현, 문제 해결, 파일 수정

#35 [feat/#33] - supabase.tsx
  package.json
  src/api/supabase.ts
  src/types/index.ts
  yarn.lock
Labels: 파일 수정

#39 Feat/apply - 마이페이지 [스크랩 사진 정렬 , 수정 모달창 퍼블리싱], 예약신청페이지 이미지 띄우기 구현
  src/api/supabase.ts
  src/app/globals.css
  src/app/mypage/[userId]/page.tsx
  src/components/apply/ApplyPageOne.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/HospitalImage.tsx
  src/components/apply/HospitalName.tsx
  src/components/layout/Tabs.tsx
  src/components/layout/TopNavbar.tsx
  src/components/mypage/MyPageTab.tsx
  src/components/mypage/ReservationInfoItem.tsx
  src/components/mypage/ScrappedList.tsx
Labels: 기능 구현, 문제 해결

#42 병원 리스트 페이지, 상담 페이지 오류 수정
  src/api/supabase.ts
  src/app/map/[hospitalId]/page.tsx
  src/app/map/[hospitalId]/review/page.tsx
  src/app/selftest/page.tsx
  src/assets/icons/filled_star.png
  src/assets/icons/hollow_star.png
  src/components/consult/AskForm.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/review/ReviewForm.tsx
  src/components/map/review/ReviewItem.tsx
  src/components/map/review/ReviewRating.tsx
  src/components/map/review/ReviewRecent.tsx
  src/components/map/review/ReviewTags.tsx
  src/types/index.ts
  src/types/supabase.ts
  src/utils/getUserInfo.ts
Labels: 기능 구현, 문제 해결, 파일 수정

#43 Feat/apply - 마이페이지, 자가진단 페이지 퍼블리싱 완료
  src/app/selftest/page.tsx
  src/components/mypage/ReservationInfoItem.tsx
  src/components/selftest/BodyParts.tsx
  src/components/selftest/Departments.tsx
  src/components/selftest/Genders.tsx
  src/components/selftest/Symptoms.tsx
  src/components/selftest/TestResult.tsx
Labels: 기능 구현, 문제 해결, 파일 수정

#44 답변 대기/완료, review hospital detail page 기본정보 퍼블리싱
  package.json
  src/api/supabase.ts
  src/app/consult/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/assets/icons/filled_star.png
  src/assets/icons/hollow_star.png
  src/assets/icons/notice_btn.png
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/defaultTab/Notice.tsx
  src/components/map/defaultTab/ProgramInfo.tsx
  src/components/map/defaultTab/ReviewImageList.tsx
  src/components/map/defaultTab/ReviewList.tsx
  src/components/map/review/ReviewItem.tsx
  yarn.lock
Labels: 기능 구현

#47 Feat/apply - 실시간상담 페이지 퍼블리싱 작업 중
  src/app/consult/[consultId]/page.tsx
  src/app/consult/page.tsx
  src/app/home/page.tsx
  src/components/apply/CalendarDay.tsx
  src/components/consult/AskForm.tsx
  src/components/consult/ConsultTabs.tsx
  src/components/layout/AnswerComplete.tsx
  src/components/layout/AnswerWaiting.tsx
  src/components/layout/RoundTabs.tsx
  src/components/map/defaultTab/ProgramInfo.tsx
  src/utils/hashtag.tsx
Labels: 기능 구현

#49 메인 페이지 - 후기, 자가진단 CSS 구현 및 일부 CSS 수정
  src/api/supabase.ts
  src/app/consult/[consultId]/page.tsx
  src/app/home/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/assets/icons/review/pencil.png
  src/components/consult/AskForm.tsx
  src/components/consult/ConsultTabs.tsx
  src/components/home/MainPageReview.tsx
  src/components/home/SelfTest.tsx
  src/components/home/SelfTestWidget.tsx
  src/components/layout/RoundTabs.tsx
  src/components/map/defaultTab/ReviewImageList.tsx
  src/components/map/defaultTab/ReviewList.tsx
  src/components/map/review/ReviewItem.tsx
  src/components/map/review/ReviewRecent.tsx
  src/components/mypage/AdminQuestionItem.tsx
  src/components/mypage/MyQuestionItem.tsx
  src/components/mypage/ReservationInfoItem.tsx
  src/components/mypage/ScrappedList.tsx
Labels: 기능 구현, 파일 수정

#51 home에 consult 페이지 넣기, mypage 답변 완료/대기중, askform consultId 에러
  src/api/supabase.ts
  src/app/consult/page.tsx
  src/app/home/page.tsx
  src/components/consult/AskForm.tsx
  src/components/home/consult/ConsultItem.tsx
  src/components/home/consult/ConsultList.tsx
  src/components/home/consult/HomeConsultItem.tsx
  src/components/home/consult/HomeConsultList.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/mypage/MyQuestionItem.tsx
Labels: 기능 구현

#52 메인 페이지 : 후기, 실시간 상담 부분 수정
  next.config.mjs
  postcss.config.js
  src/app/home/page.tsx
  src/app/mypage/[userId]/page.tsx
  src/assets/icons/defaultImage.png
  src/components/consult/AskForm.tsx
  src/components/consult/ConsultTabs.tsx
  src/components/home/MainPageReview.tsx
  src/components/home/consult/HomeConsultItem.tsx
  src/components/home/consult/HomeConsultList.tsx
  src/components/map/defaultTab/ReviewList.tsx
  src/components/mypage/AdminMenu.tsx
Labels: 기능 구현, 파일 수정

#55 consult Image 홈화면에 띄우기
  src/components/home/consult/HomeConsultItem.tsx
  src/components/mypage/MyQuestionItem.tsx
Labels: 기능 구현

#59 Review
  package.json
  src/api/supabase.ts
  src/app/consult/[consultId]/page.tsx
  src/app/consult/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/app/map/[hospitalId]/review/page.tsx
  src/app/mypage/[userId]/page.tsx
  src/components/apply/ApplyPageOne.tsx
  src/components/apply/CalendarDay.tsx
  src/components/consult/AskForm.tsx
  src/components/consult/ConsultAnswerForm.tsx
  src/components/home/MainPageReview.tsx
  src/components/home/consult/HomeConsultItem.tsx
  src/components/layout/Tabs.tsx
  src/components/map/HospitalMainInfo.tsx
  src/components/map/Map.tsx
  src/components/map/defaultTab/DefaultTab.tsx
  src/components/map/defaultTab/ReviewImageList.tsx
  src/components/map/review/ReviewForm.tsx
  src/components/map/review/ReviewRating.tsx
  src/components/map/reviewTab/ReviewTab.tsx
  src/components/mypage/MyQuestionItem.tsx
  src/components/mypage/ScrappedList.tsx
  src/components/selftest/TestResult.tsx
  src/hooks/getMyConsultData.ts
  src/types/index.ts
  src/types/supabase.ts
  src/utils/drawKakaoMap.ts
  tsconfig.json
  yarn.lock
Labels: 기능 구현, 파일 수정

#77 [fix] 빌드 에러 수정 중
  src/app/map/[hospitalId]/page.tsx
  src/app/selftest/page.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/map/defaultTab/ReviewList.tsx
  src/components/mypage/MyQuestionItem.tsx
Labels: 문제 해결, 파일 수정

#82 필요없는 파일, console.log 제거
  src/api/supabase.ts
  src/app/consult/page.tsx
  src/app/login/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/app/selftestresult/page.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/CalendarDay.tsx
  src/components/apply/CourseSelect.tsx
  src/components/apply/GetNewData.tsx
  src/components/apply/HospitalImage.tsx
  src/components/apply/HospitalName.tsx
  src/components/consult/AskForm.tsx
  src/components/consult/ConsultAnswerForm.tsx
  src/components/consult/ConsultImages.tsx
  src/components/consult/ConsultItem.tsx
  src/components/consult/ConsultQuestion.tsx
  src/components/consult/ConsultTabs.tsx
  src/components/consult/HashTags.tsx
  src/components/home/FindHospital.tsx
  src/components/home/consult/HomeConsultItem.tsx
  src/components/home/search/FindHospitalRegionBtn.tsx
  src/components/layout/Navbar.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/HospitalMainInfo.tsx
  src/components/map/defaultTab/DefaultTab.tsx
  src/components/map/defaultTab/Notice.tsx
  src/components/map/imageTab/ImageTab.tsx
  src/components/map/review/ReviewForm.tsx
  src/components/map/review/ReviewItem.tsx
  src/components/map/review/ReviewRating.tsx
  src/components/map/review/ReviewRecent.tsx
  src/components/map/review/ReviewTags.tsx
  src/components/map/reviewTab/ReviewTab.tsx
  src/components/mypage/AdminMenu.tsx
  src/components/mypage/AdminQuestionItem.tsx
  src/components/mypage/MyQuestionItem.tsx
  src/components/mypage/ReservationInfoItem.tsx
  src/components/mypage/ReservationInfoList.tsx
  src/components/selftest/Genders.tsx
  src/components/selftest/Symptoms.tsx
  src/components/selftest/TestResult.tsx
  src/utils/changeScrappedList.ts
  src/utils/changeTimeFormat.ts
Labels: 파일 수정

#83 홈화면, 마이페이지, 실시시간 상담페이지 맵 리스트 퍼블리싱
  src/api/supabase.ts
  src/app/consult/[consultId]/page.tsx
  src/app/consult/page.tsx
  src/app/globals.css
  src/app/home/page.tsx
  src/app/login/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/app/map/page.tsx
  src/app/mypage/[userId]/page.tsx
  src/app/selftest/page.tsx
  src/app/selftestresult/page.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/CalendarDay.tsx
  src/components/apply/CourseSelect.tsx
  src/components/apply/GetNewData.tsx
  src/components/apply/HospitalImage.tsx
  src/components/apply/HospitalName.tsx
  src/components/consult/AskForm.tsx
  src/components/consult/ConsultAnswerForm.tsx
  src/components/consult/ConsultImages.tsx
  src/components/consult/ConsultItem.tsx
  src/components/consult/ConsultQuestion.tsx
  src/components/consult/ConsultTabs.tsx
  src/components/consult/HashTags.tsx
  src/components/home/FindHospital.tsx
  src/components/home/HospitalListView.tsx
  src/components/home/MainPageReview.tsx
  src/components/home/SelfTestWidget.tsx
  src/components/home/consult/HomeConsultItem.tsx
  src/components/home/consult/HomeConsultList.tsx
  src/components/home/search/FindHospitalRegionBtn.tsx
  src/components/layout/Navbar.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/HospitalMainInfo.tsx
  src/components/map/defaultTab/DefaultTab.tsx
  src/components/map/defaultTab/Notice.tsx
  src/components/map/imageTab/ImageTab.tsx
  src/components/map/review/ReviewForm.tsx
  src/components/map/review/ReviewItem.tsx
  src/components/map/review/ReviewRating.tsx
  src/components/map/review/ReviewRecent.tsx
  src/components/map/review/ReviewTags.tsx
  src/components/map/reviewTab/ReviewTab.tsx
  src/components/mypage/AccessDenied.tsx
  src/components/mypage/AdminMenu.tsx
  src/components/mypage/AdminQuestionItem.tsx
  src/components/mypage/MyQuestionItem.tsx
  src/components/mypage/ReservationInfoItem.tsx
  src/components/mypage/ReservationInfoList.tsx
  src/components/selftest/Genders.tsx
  src/components/selftest/Symptoms.tsx
  src/components/selftest/TestResult.tsx
  src/utils/changeScrappedList.ts
  src/utils/changeTimeFormat.ts
  src/utils/hashtag.tsx
Labels: 기능 구현

#84 [feat] - consult text 요약, 퍼블리싱작업 남은것 하는중
  src/app/consult/[consultId]/page.tsx
  src/app/consult/page.tsx
  src/app/globals.css
  src/app/home/page.tsx
  src/app/login/page.tsx
  src/app/map/page.tsx
  src/app/mypage/[userId]/page.tsx
  src/app/selftest/page.tsx
  src/components/apply/ApplyPageOne.tsx
  src/components/apply/CalendarDay.tsx
  src/components/consult/AskForm.tsx
  src/components/consult/ConsultQuestion.tsx
  src/components/home/FindHospital.tsx
  src/components/home/HospitalListView.tsx
  src/components/home/MainPageReview.tsx
  src/components/home/SelfTestWidget.tsx
  src/components/home/consult/HomeConsultItem.tsx
  src/components/home/consult/HomeConsultList.tsx
  src/components/layout/Navbar.tsx
  src/components/layout/Slider.tsx
  src/components/mypage/AccessDenied.tsx
  src/components/mypage/MyQuestionItem.tsx
  src/utils/hashtag.tsx
Labels: 기능 구현, 문제 해결

#88 navbar에 다른 컴포넌트 가려지는 것 수정
  src/app/consult/[consultId]/page.tsx
  src/app/consult/page.tsx
  src/app/globals.css
  src/app/login/page.tsx
  src/app/map/[hospitalId]/review/page.tsx
  src/app/selftest/page.tsx
  src/components/apply/ApplyPageFour.tsx
  src/components/apply/ApplyPageOne.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/ApplyPageTwo.tsx
  src/components/consult/AskForm.tsx
  src/components/consult/ConsultAnswerForm.tsx
  src/components/home/FindHospital.tsx
  src/components/home/HospitalListView.tsx
  src/components/home/MainPageReview.tsx
  src/components/home/SelfTestWidget.tsx
  src/components/home/consult/HomeConsultList.tsx
  src/components/home/search/FindHospitalRegionBtn.tsx
  src/components/layout/Navbar.tsx
  src/components/layout/Slider.tsx
  src/components/layout/TopNavbar.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/defaultTab/ReviewList.tsx
  src/components/map/hospitalList/HospitalItem.tsx
  src/components/map/review/ReviewItem.tsx
  src/components/selftest/Symptoms.tsx
  src/components/selftest/TestResult.tsx
Labels: 문제 해결, 파일 수정

#92 Feat/apply - 메인페이지 퍼블리싱 작업, 예약페이지 파일수정, 아이콘 변경
  package-lock.json
  package.json
  src/app/apply/[hospitalId]/page.tsx
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/assets/icons/HomeIndicator.png
  src/assets/icons/StatusBar.png
  src/assets/icons/consultIcon.png
  src/assets/icons/googlelogin.png
  src/assets/icons/homeIcon.png
  src/assets/icons/kakaologin.png
  src/assets/icons/loginIcon.png
  src/assets/icons/logoutIcon.png
  src/assets/icons/main/강원.png
  src/assets/icons/main/경기.png
  src/assets/icons/main/경상.png
  src/assets/icons/main/서울.png
  src/assets/icons/main/인천.png
  src/assets/icons/main/전라.png
  src/assets/icons/main/제주.png
  src/assets/icons/main/충청.png
  src/assets/icons/modal/warning.png
  src/assets/icons/mypageIcon.png
  src/assets/icons/selftest/Female_checked.png
  src/assets/icons/selftest/Female_not_checked.png
  src/assets/icons/selftest/Male_checked.png
  src/assets/icons/selftest/Male_not_checked.png
  src/assets/icons/testIcon.png
  src/components/apply/ApplyPageOne.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/CalendarDay.tsx
  src/components/apply/CourseSelect.tsx
  src/components/apply/GetNewData.tsx
  src/components/apply/HospitalImage.tsx
  src/components/apply/TimeSelect.tsx
  src/components/home/HospitalListView.tsx
  src/components/home/search/FindHospitalRegionBtn.tsx
  src/components/layout/Buttons.tsx
  src/components/layout/CheckIcons.tsx
  src/components/layout/Navbar.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/defaultTab/ProgramInfo.tsx
  src/components/map/hospitalList/HospitalItem.tsx
  src/components/map/hospitalList/HospitalList.tsx
  src/components/map/imageTab/ImageTab.tsx
  src/components/map/review/ReviewForm.tsx
  src/components/mypage/MyQuestionItem.tsx
  src/components/mypage/ReservationInfoItem.tsx
  src/components/selftest/Departments.tsx
  src/shared/zustand/applyStore.ts
  src/shared/zustand/selftestStore.ts
  src/types/supabase.ts
  yarn.lock
Labels: 기능 구현, 문제 해결, 파일 수정

#93 메인페이지 퍼블리싱 작업, 예약페이지 파일수정, 아이콘 변경
  package-lock.json
  package.json
  src/app/apply/[hospitalId]/page.tsx
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/assets/icons/HomeIndicator.png
  src/assets/icons/StatusBar.png
  src/assets/icons/consultIcon.png
  src/assets/icons/googlelogin.png
  src/assets/icons/homeIcon.png
  src/assets/icons/kakaologin.png
  src/assets/icons/loginIcon.png
  src/assets/icons/logoutIcon.png
  src/assets/icons/main/강원.png
  src/assets/icons/main/경기.png
  src/assets/icons/main/경상.png
  src/assets/icons/main/서울.png
  src/assets/icons/main/인천.png
  src/assets/icons/main/전라.png
  src/assets/icons/main/제주.png
  src/assets/icons/main/충청.png
  src/assets/icons/modal/warning.png
  src/assets/icons/mypageIcon.png
  src/assets/icons/selftest/Female_checked.png
  src/assets/icons/selftest/Female_not_checked.png
  src/assets/icons/selftest/Male_checked.png
  src/assets/icons/selftest/Male_not_checked.png
  src/assets/icons/testIcon.png
  src/components/apply/ApplyPageOne.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/CalendarDay.tsx
  src/components/apply/CourseSelect.tsx
  src/components/apply/GetNewData.tsx
  src/components/apply/HospitalImage.tsx
  src/components/apply/TimeSelect.tsx
  src/components/home/HospitalListView.tsx
  src/components/home/search/FindHospitalRegionBtn.tsx
  src/components/layout/Buttons.tsx
  src/components/layout/CheckIcons.tsx
  src/components/layout/Navbar.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/defaultTab/ProgramInfo.tsx
  src/components/map/hospitalList/HospitalItem.tsx
  src/components/map/hospitalList/HospitalList.tsx
  src/components/map/imageTab/ImageTab.tsx
  src/components/map/review/ReviewForm.tsx
  src/components/mypage/MyQuestionItem.tsx
  src/components/mypage/ReservationInfoItem.tsx
  src/components/selftest/Departments.tsx
  src/shared/zustand/applyStore.ts
  src/shared/zustand/selftestStore.ts
  src/types/supabase.ts
  yarn.lock
Labels: 기능 구현, 문제 해결, 파일 수정

#94 [fix] build error 수정
  src/components/map/imageTab/ImageTab.tsx
  src/components/mypage/MyQuestionItem.tsx
Labels: 문제 해결

#99 Main - Merge
  src/api/supabase.ts
  src/app/consult/[consultId]/page.tsx
  src/app/consult/page.tsx
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/app/map/[hospitalId]/review/page.tsx
  src/app/map/page.tsx
  src/app/mypage/[userId]/page.tsx
  src/app/providers.tsx
  src/app/selftest/page.tsx
  src/app/selftestresult/page.tsx
  src/assets/landing/Page1.png
  src/assets/landing/Page2.png
  src/assets/landing/Page3.png
  src/assets/landing/Page4.png
  src/components/apply/ApplyPageOne.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/ApplyPageTwo.tsx
  src/components/apply/CalendarDay.tsx
  src/components/apply/CourseSelect.tsx
  src/components/apply/HospitalName.tsx
  src/components/apply/TimeSelect.tsx
  src/components/consult/AskForm.tsx
  src/components/consult/ConsultAnswerForm.tsx
  src/components/consult/ConsultTabs.tsx
  src/components/landing/LandingPageFour.tsx
  src/components/landing/LandingPageOne.tsx
  src/components/landing/LandingPageThree.tsx
  src/components/landing/LandingPageTwo.tsx
  src/components/layout/CheckIcons.tsx
  src/components/layout/MobileScreen.tsx
  src/components/layout/RoundTabs.tsx
  src/components/layout/Slider.tsx
  src/components/layout/Tabs.tsx
  src/components/layout/TopNavbar.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/defaultTab/Notice.tsx
  src/components/map/hospitalList/HospitalItem.tsx
  src/components/map/hospitalList/HospitalList.tsx
  src/components/map/review/ReviewForm.tsx
  src/components/map/review/ReviewItem.tsx
  src/components/map/review/ReviewRecent.tsx
  src/components/mypage/AdminMenu.tsx
  src/components/mypage/MyPageTab.tsx
  src/components/mypage/ReservationInfoItem.tsx
  src/components/mypage/ReservationInfoList.tsx
  src/components/mypage/ScrappedList.tsx
  src/components/selftest/BodyParts.tsx
  src/components/selftest/Departments.tsx
  src/components/selftest/Genders.tsx
  src/components/selftest/Symptoms.tsx
  src/components/selftest/TestResult.tsx
  src/shared/zustand/applyStore.ts
Labels: 기능 구현, 문제 해결, 파일 수정

#100 CSS 오류 재 수정
  src/components/mypage/ReservationInfoItem.tsx
Labels: 파일 수정

#101 CSS 오류 재 수정
  src/components/mypage/ReservationInfoItem.tsx
Labels: 파일 수정

#103 [feat/#102] - 네브바 홈 아이콘 수정, 로그인페이지 로고 적용, 랜딩페이지 폰트 수정, 마이페이지 예약수정 모달창 - CSS수정
  src/app/layout.tsx
  src/app/login/page.tsx
  src/components/landing/LandingPageFour.tsx
  src/components/landing/LandingPageOne.tsx
  src/components/landing/LandingPageThree.tsx
  src/components/landing/LandingPageTwo.tsx
  src/components/layout/CheckIcons.tsx
  src/components/mypage/ReservationInfoItem.tsx
Labels: 문제 해결, 파일 수정

#104 네브바 홈 아이콘 수정, 로그인페이지 로고 적용, 랜딩페이지 폰트 수정, 마이페이지 예약수정 - CSS 수정
  src/app/layout.tsx
  src/app/login/page.tsx
  src/components/landing/LandingPageFour.tsx
  src/components/landing/LandingPageOne.tsx
  src/components/landing/LandingPageThree.tsx
  src/components/landing/LandingPageTwo.tsx
  src/components/layout/CheckIcons.tsx
  src/components/mypage/ReservationInfoItem.tsx
Labels: 문제 해결, 파일 수정

#107 [fix] - 병원 상세페이지, consult 페이지 퍼블리싱 수정중
  src/api/supabase.ts
  src/app/consult/[consultId]/page.tsx
  src/app/consult/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/app/map/[hospitalId]/review/page.tsx
  src/assets/icons/notice_btn.png
  src/components/consult/AskForm.tsx
  src/components/consult/ConsultTabs.tsx
  src/components/home/consult/HomeConsultItem.tsx
  src/components/layout/CheckIcons.tsx
  src/components/layout/PageBackBtn.tsx
  src/components/layout/RoundTabs.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/defaultTab/Notice.tsx
  src/components/map/defaultTab/ReviewList.tsx
  src/components/map/hospitalList/HospitalItem.tsx
  src/components/map/review/ReviewForm.tsx
  src/components/map/review/ReviewItem.tsx
  src/components/map/review/ReviewRecent.tsx
  src/components/map/review/ReviewTags.tsx
  src/utils/hashtag.tsx
Labels: 기능 구현, 파일 수정

#108 [feat] - 랜딩페이지 코드수정 및 예약신청(코스선택)페이지 버튼 위치조정
  src/assets/icons/IcIcon.png
  src/components/apply/ApplyPageThree.tsx
  src/components/landing/LandingPageFour.tsx
  src/components/landing/LandingPageOne.tsx
  src/components/landing/LandingPageThree.tsx
  src/components/landing/LandingPageTwo.tsx
Labels: 파일 수정

#110 자가진단 페이지 이미지 추가 및 오류 수정
  src/app/selftest/page.tsx
  src/assets/icons/selftest/abdomen_disease.jpeg
  src/assets/icons/selftest/back_disease.jpeg
  src/assets/icons/selftest/chest_disease.jpeg
  src/assets/icons/selftest/neck_disease.jpeg
  src/assets/icons/selftest/nose_disease.jpeg
  src/components/layout/CheckIcons.tsx
  src/components/selftest/BodyParts.tsx
  src/components/selftest/Departments.tsx
  src/components/selftest/Symptoms.tsx
  src/components/selftest/TestResult.tsx
Labels: 기능 구현, 문제 해결, 파일 수정

#112 review 유저 이름 , 예약 시 로그인 확인
  src/api/supabase.ts
  src/app/consult/[consultId]/page.tsx
  src/app/consult/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/app/map/[hospitalId]/review/page.tsx
  src/app/selftest/page.tsx
  src/assets/icons/IcIcon.png
  src/assets/icons/notice_btn.png
  src/assets/icons/selftest/abdomen_disease.jpeg
  src/assets/icons/selftest/back_disease.jpeg
  src/assets/icons/selftest/chest_disease.jpeg
  src/assets/icons/selftest/neck_disease.jpeg
  src/assets/icons/selftest/nose_disease.jpeg
  src/components/apply/ApplyPageThree.tsx
  src/components/consult/AskForm.tsx
  src/components/consult/ConsultTabs.tsx
  src/components/home/consult/HomeConsultItem.tsx
  src/components/landing/LandingPageFour.tsx
  src/components/landing/LandingPageOne.tsx
  src/components/landing/LandingPageThree.tsx
  src/components/landing/LandingPageTwo.tsx
  src/components/layout/CheckIcons.tsx
  src/components/layout/PageBackBtn.tsx
  src/components/layout/RoundTabs.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/Map.tsx
  src/components/map/defaultTab/Notice.tsx
  src/components/map/defaultTab/ReviewList.tsx
  src/components/map/hospitalList/HospitalItem.tsx
  src/components/map/review/ReviewForm.tsx
  src/components/map/review/ReviewItem.tsx
  src/components/map/review/ReviewRecent.tsx
  src/components/map/review/ReviewTags.tsx
  src/components/selftest/BodyParts.tsx
  src/components/selftest/Departments.tsx
  src/components/selftest/Symptoms.tsx
  src/components/selftest/TestResult.tsx
  src/types/supabase.ts
  src/utils/hashtag.tsx
Labels: 기능 구현

#117 [feat] - 예약 시, 회원가입하면 유저 정보 넣기
  src/components/consult/ConsultTabs.tsx
  src/components/home/consult/HomeConsultItem.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/Map.tsx
  src/components/map/hospitalList/HospitalItem.tsx
  src/components/map/review/ReviewRecent.tsx
  src/types/supabase.ts
Labels: 기능 구현, 문제 해결

#118 Feat/apply - 캘린더 수정 및 잉여파일 삭제
  src/app/mypage/[userId]/page.tsx
  src/assets/icons/check.png
  src/assets/icons/consult/answer_complete.png
  src/assets/icons/consult/answer_wait.png
  src/assets/icons/consult/imagebox.png
  src/assets/icons/consult/okBtn.png
  src/assets/icons/consult/searchbar.png
  src/assets/icons/consult/selectDiagnosis.png
  src/assets/icons/review/review_okBtn.png
  src/assets/icons/review/review_searchbar.png
  src/assets/icons/selftest/progress_step1.png
  src/assets/icons/selftest/progress_step2.png
  src/assets/icons/selftest/progress_step3.png
  src/assets/icons/selftest/progress_step4.png
  src/assets/icons/xmark.png
  src/assets/upanddown/Back.png
  src/assets/upanddown/DownToggle.png
  src/assets/upanddown/Next.png
  src/assets/upanddown/UpToggle.png
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/CalendarDay.tsx
  src/components/apply/GetNewData.tsx
  src/components/apply/TimeSelect.tsx
  src/components/layout/CheckIcons.tsx
  src/components/layout/TopNavbar.tsx
Labels: 파일 수정

#123 consult 페이지 회원 유무
  src/app/consult/page.tsx
  src/components/map/HospitalInfoHeader.tsx
Labels: 기능 구현

#126 [feat] - 파비콘
  public/medidoc_logo.png
  public/next.svg
  public/vercel.svg
  src/app/favicon.ico
  src/app/layout.tsx
Labels: 기능 구현

#128 Feat/apply - 상세 & 실시간상담 페이지 퍼블리싱(위치 조정), 랜딩페이지 퍼블리싱, 캘린더 퍼블리싱(날짜 위치 조정)
  src/app/consult/page.tsx
  src/app/globals.css
  src/app/login/page.tsx
  src/components/apply/CalendarDay.tsx
  src/components/home/consult/HomeConsultItem.tsx
  src/components/layout/CheckIcons.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/defaultTab/ProgramInfo.tsx
  src/utils/hashtag.tsx
Labels: 문제 해결, 파일 수정

#131 Merge 오류 수정
  src/components/consult/AskForm.tsx
  src/components/home/FindHospital.tsx
Labels: 문제 해결

#133 Feat/mainpage - 병원 상세페이지 리뷰쓰기 위치 조정
  src/app/consult/page.tsx
  src/app/globals.css
  src/app/login/page.tsx
  src/components/apply/CalendarDay.tsx
  src/components/home/consult/HomeConsultItem.tsx
  src/components/layout/CheckIcons.tsx
  src/components/map/defaultTab/ProgramInfo.tsx
  src/components/map/defaultTab/ReviewList.tsx
  src/utils/hashtag.tsx
Labels: 파일 수정
